//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTraderWPF.DBs
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureValue
    {
        public int Id { get; set; }
        public int DataSourceId { get; set; }
        public System.DateTime Date { get; set; }
        public double Value { get; set; }
    
        public virtual DataSource DataSource { get; set; }
    }
}
