//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTraderWPF.DBs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symbol
    {
        public Symbol()
        {
            this.Trades = new HashSet<Trade>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Trade> Trades { get; set; }
    }
}
