//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTraderWPF.DBs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int Id { get; set; }
        public double Price { get; set; }
        public string Date { get; set; }
        public int SymbolId { get; set; }
        public int Type { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> TradeId { get; set; }
        public Nullable<double> AvgPrice { get; set; }
    
        public virtual Symbol Symbol { get; set; }
    }
}
